### PR TITLE
WIP: Implement Sealed Boxes (closes #120)

### LINKED ISSUE #120: Request support for libsodium crypto_box_seal and crypto_box_seal_open
Would it be possible to add support for sealed boxes which were recently added to libsodium in v1.0.3?

https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html

Also, in light of this addition, the second wiki entry about mutual authentication now seems too strong. No?

https://github.com/cryptosphere/rbnacl/wiki/Frequently-Asked-Questions

```
Q: Is there any way to decrypt a Crypto::Box message with only a private key without requiring the public key of the sender?

A: No, and there never will be. This is an integral part of how the Curve25519 algorithm operates, and the mutual authentication it provides is a design principle you should consider whenever using public key cryptography.
```

### PR DESCRIPTION
**Pull request by robbat2**
Implement Sealed Boxes.

Requires >=libsodium-1.0.3.

TODO before merging:
- finish docs
- handle error case for too-old libsodium

See: https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html
Closes: https://github.com/cryptosphere/rbnacl/issues/120
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>

### CODE REVIEW

**Comment by robbat2** [comment]
Testsuite design problem: sealed boxes use an ephemeral secret key, and the libsodium API does not let you manually pass a key in for this, as a result the ciphertext output cannot be made deterministic for testing.

**Comment by tarcieri** [comment]
That's rather unfortunate. I've solved similar problems by allowing the API to accept a user-supplied RNG for deriving the ephemeral key. Might be worth opening a libsodium issue about.

**Comment by robbat2** [comment]
Opened in libsodium: https://github.com/jedisct1/libsodium/issues/657

**Comment by tarcieri** [comment]
Per https://github.com/jedisct1/libsodium/issues/657 it sounds like the best option is to change out libsodium's global RNG for the purposes of running the tests for sealed boxes. Ideally the rest of the test suite shouldn't be affected by this

**Comment by tarcieri** [comment]
@robbat2 any interest in continuing this?

An easy way to write tests for it:

- Use a static test vector to test decryption/unsealing/opening, which should avoid non-determinism in the test
- Test encryption by making sure the decryption function can decrypt a randomly sealed box as opposed to using a test vector, i.e. make sure a encryption/decryption roundtrip operation works

I'm planning on releasing RbNaCl 6.0 sometime in the next few months, and this would be nice to have

**Comment by robbat2** [comment]
Probably good to have both of those tests, I don't have time right now however

**Comment by gogocurtis** [comment]
Would you accept a testing solution that implemented a functional end to end test over the expected behaviour of crypto_box_seal ? 

ie: (pseudo code)
```

let(:public_key) {}
let(:private_key {}

it " round-trips correctly" do
crytpo_text = crypto_box_seal(expected_message, public_key)
actual_message = crypto_box_open(message, private_key)
expect(actual_message).to eq(expected_message)
end

```

**Comment by tarcieri** [comment]
Looks like this is obsoleted by #184

**Pull request closed without merging**
